# Site settings
title: TastWerk.Berlin
email: info@tastwerk.berlin
description: > # this means to ignore newlines until "baseurl:"
   Willkommen beim TastWerk Berlin!
   Unsere Seite befindet sich noch im Aufbau.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tastwerk.berlin" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

sass:
    sass_dir: _vendor
    style: :compressed
